apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Or Delete, depending on your needs
  storageClassName: gp3
  volumeMode: Filesystem
  # Replace with the actual AWS EBS volume ID
  awsElasticBlockStore:
    volumeID: <your-aws-ebs-volume-id>
    fsType: ext4 # Or your desired filesystem type
